// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvWr-HIzZKxjDtPRmO9y3w9K-PqObtHz0',
    appId: '1:675905775251:web:cbbfa3846727dc8877cf66',
    messagingSenderId: '675905775251',
    projectId: 'travel-loco-2b778',
    authDomain: 'travel-loco-2b778.firebaseapp.com',
    storageBucket: 'travel-loco-2b778.firebasestorage.app',
    measurementId: 'G-01DWH19RR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcfaN3h5tINVJP8wSa0GiZJdcrCNEF_6A',
    appId: '1:675905775251:android:9af01c2742cc16bc77cf66',
    messagingSenderId: '675905775251',
    projectId: 'travel-loco-2b778',
    storageBucket: 'travel-loco-2b778.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAze0Tl36R9KX_iJSmlyE_yzl8qTbYU7Rc',
    appId: '1:675905775251:ios:226bb897e8dbb41777cf66',
    messagingSenderId: '675905775251',
    projectId: 'travel-loco-2b778',
    storageBucket: 'travel-loco-2b778.firebasestorage.app',
    iosBundleId: 'com.example.travelLoco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAze0Tl36R9KX_iJSmlyE_yzl8qTbYU7Rc',
    appId: '1:675905775251:ios:226bb897e8dbb41777cf66',
    messagingSenderId: '675905775251',
    projectId: 'travel-loco-2b778',
    storageBucket: 'travel-loco-2b778.firebasestorage.app',
    iosBundleId: 'com.example.travelLoco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvWr-HIzZKxjDtPRmO9y3w9K-PqObtHz0',
    appId: '1:675905775251:web:05a34ec17fd245d277cf66',
    messagingSenderId: '675905775251',
    projectId: 'travel-loco-2b778',
    authDomain: 'travel-loco-2b778.firebaseapp.com',
    storageBucket: 'travel-loco-2b778.firebasestorage.app',
    measurementId: 'G-D6WDQJGPVZ',
  );

}